FROM balenalib/raspberry-pi-debian:latest

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["scripts/start.sh"]
